blog/config/routes.rb
Rails.application.routes.draw do
  # get 'cay_thuoc_nams/index'
  devise_for :users
  root "cay_thuoc_nams#index"
  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"

  resources :articles
  resources :cay_thuoc_nams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

blog/app/models/article.rb
class Article < ApplicationRecord
    scope :has_keyword, ->(keyword) { where("title like ?", "%#{keyword}%") }
end

blog/app/models/cay_thuoc_nam.rb
class CayThuocNam < ApplicationRecord
    scope :has_keyword, ->(keyword) { where("ten like ?", "%#{keyword}%") }
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    # laays hets duw lieu ra
    @demo = params[:demo]
    @articles = Article.has_keyword(@demo)

  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end


  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

blog/app/controllers/cay_thuoc_nams_controller.rb
class CayThuocNamsController < ApplicationController
  def index
    # laays hets duw lieu ra
    @demo = params[:demo]
    @cay_thuoc_nams = CayThuocNam.has_keyword(@demo)

  end

  def show
    @cay_thuoc_nams = CayThuocNam.find(params[:id])
  end

  def new
    @cay_thuoc_nams = CayThuocNam.new
  end


  def create
    @cay_thuoc_nams = CayThuocNam.new(cay_thuoc_nam_params)

    if @cay_thuoc_nams.save
      redirect_to @cay_thuoc_nams
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @cay_thuoc_nam = CayThuocNam.find(params[:id])
  end

  def update
    @cay_thuoc_nam = CayThuocNam.find(params[:id])

    if @cay_thuoc_nam.update(cay_thuoc_nam_params)
      redirect_to @cay_thuoc_nam
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cay_thuoc_nam = CayThuocNam.find(params[:id])
    @cay_thuoc_nam.destroy

    redirect_to root_path, status: :see_other
  end

  

  private
    def cay_thuoc_nam_params
      params.require(:cay_thuoc_nam).permit(:ten, :chitiet, :giathanh, :soluong, :maula, :duoctinh, :luuy, :noitrong)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/cay_thuoc_nams_helper.rb
module CayThuocNamsHelper
end

blog/app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

blog/app/views/articles/edit.html.erb
<%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% @article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

blog/app/views/articles/index.html.erb
<p>Bang du lieu</p>


<table class="table">
  <thead class="bg-warning text-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Body</th>
      <th scope="col">Edit</th>
      <th scope="col">Del</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <th scope="row"><%= article.id %></th>
      <td>
      <a href="<%= article_path(article) %>">
        <%= article.title %>
      </a>
      </td>
      <td><%= article.body %></td>
      <td><%= link_to "Edit", edit_article_path(article) %></td>
      <td><%= link_to "Dele", article_path(article), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
    </tr>
  <% end %>
    
  </tbody>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div class="form-group">
    <label for="exampleFormControlInput1">Title</label>
    <input name="article[title]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="typing...">
  </div>

  <div class="form-group">
  <label for="exampleFormControlTextarea1">Body </label>
  <textarea name="article[body]" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>

  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

blog/app/views/cay_thuoc_nams/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

blog/app/views/cay_thuoc_nams/edit.html.erb
<%= form_with model: @cay_thuoc_nam do |form| %>
  <div class="d-flex justify-content-around">
  <div>
      <span>Tên cây</span><br>
      <%= form.text_field :ten %>
      <% @cay_thuoc_nam.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
    <span>Chi tiết cây</span><br>
      <%= form.text_area :chitiet %><br>
      <% @cay_thuoc_nam.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
    <span>Màu lá</span><br>
      <%= form.text_field :maula %><br>
      <% @cay_thuoc_nam.errors.full_messages_for(:maula).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
    


  <div class="d-flex justify-content-around">
  <div>
  <span>Dược tính</span><br>
    <%= form.text_field :duoctinh %><br>
    <% @cay_thuoc_nam.errors.full_messages_for(:duoctinh).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
  <span>Lưu ý</span><br>
    <%= form.text_field :luuy %><br>
    <% @cay_thuoc_nam.errors.full_messages_for(:luuy).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <span>Nơi trồng</span><br>
    <%= form.text_field :noitrong %><br>
    <% @cay_thuoc_nam.errors.full_messages_for(:noitrong).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  </div>

    

    <div class="m-5">
      <%= form.submit %>
    </div>
  <% end %>

blog/app/views/cay_thuoc_nams/index.html.erb
<h4>Bảng dữ liệu Cây thuốc nam</h4>


<table class="table">
  <thead class="bg-warning text-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Tên cây thuốc</th>
      <th scope="col">Chi tiết cây</th>

      <th scope="col">Màu sắc cây</th>
      <th scope="col">Dược tính</th>
      <th scope="col">Lưu ý sử dụng</th>
      <th scope="col">Nơi trồng</th>

      <th scope="col">Chỉnh sửa</th>
      <th scope="col">Xóa</th>
    </tr>
  </thead>
  <tbody>
  <% @cay_thuoc_nams.each do |caythuoc| %>
    <tr>
      <th scope="row"><%= caythuoc.id %></th>
      <td>
      <a href="<%= cay_thuoc_nam_path(caythuoc) %>">
        <%= caythuoc.ten %>
      </a>
      </td>
      <td><%= caythuoc.chitiet %></td>
      <td><%= caythuoc.maula %></td>
      <td><%= caythuoc.duoctinh %></td>
      <td><%= caythuoc.luuy %></td>
      <td><%= caythuoc.noitrong %></td>


      <td><%= link_to "Chỉnh sửa", edit_cay_thuoc_nam_path(caythuoc) %></td>
      <td><%= link_to "Xóa", cay_thuoc_nam_path(caythuoc), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
    </tr>
  <% end %>
    
  </tbody>
</table>

blog/app/views/cay_thuoc_nams/new.html.erb
<h1>Thêm một cây mới</h1>

<%= form_with model: @cay_thuoc_nams do |form| %>
  <div class="form-group">
    <label for="exampleFormControlInput1">  <b>Tên cây thuốc</b></label>
    <input name="cay_thuoc_nam[ten]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="nhập tên...">
  </div>

  <div class="form-group">
  <label for="exampleFormControlTextarea1"> <b>Mô tả chi tiết cây</b></label>
  <textarea name="cay_thuoc_nam[chitiet]" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

<div class="form-group">
  <label for="exampleFormControlTextarea1"> <b>Màu sắc cây</b></label>
  <input name="cay_thuoc_nam[maula]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="typing...">
</div>

<div class="form-group">
  <label for="exampleFormControlTextarea1"><b>Dược tính</b></label>
  <input name="cay_thuoc_nam[duoctinh]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="typing...">
</div>

<div class="form-group">
  <label for="exampleFormControlTextarea1"><b>Lưu ý sử dụng</b></label>
  <input name="cay_thuoc_nam[luuy]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="typing...">
</div>

<div class="form-group">
  <label for="exampleFormControlTextarea1"><b>Nơi trồng</b></label>
  <input name="cay_thuoc_nam[noitrong]" type="text" class="form-control" id="exampleFormControlInput1" placeholder="typing...">
</div>


  <div class="my-5">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/cay_thuoc_nams/show.html.erb
<h1>  Tên cây thuốc: <%= @cay_thuoc_nams.ten %></h1>

<h6>  Mô tả cây thuốc: <%= @cay_thuoc_nams.chitiet %></h6>
<h6>  Màu sắc: <%= @cay_thuoc_nams.maula %></h6>
<h6>  Dược tính: <%= @cay_thuoc_nams.duoctinh %></h6>
<h6>  Lưu ý: <%= @cay_thuoc_nams.luuy %></h6>
<h6>  Nơi trồng: <%= @cay_thuoc_nams.noitrong %></h6>

<ul>
  <li><%= link_to "Edit", edit_cay_thuoc_nam_path(@cay_thuoc_nams) %></li>

  <li><%= link_to "Destroy", cay_thuoc_nam_path(@cay_thuoc_nams), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    
    <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="/cay_thuoc_nams">Trang chủ<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/cay_thuoc_nams/new">Thêm mới</a>
      </li>
    </ul>

    <form action="/cay_thuoc_nams" method="get" class="form-inline my-2 my-lg-0">
      <input name="demo" value='<%= @demo %>' class="form-control mr-sm-2" type="search" placeholder="Tìm kiếm" aria-label="Search">
      <button class="btn btn-outline-white my-2 my-sm-0" type="submit">Tìm kiếm</button>
    </form>

    <form class="login mx-3">
    <select class="custom-select" id="inputGroupSelect01">
    <option selected>Thu Hòa</option>
    <option value="1">Đăng nhập</option>
    <option value="2">Đăng xuất</option>
  </select>
    </form>
  </div>
</nav>

  <div class="container">
  <% if user_signed_in? %> 
 <div> Xin chào bạn:  <%= current_user.email %> đã đến với trang web của chúng tôi!</div> 
  <%= button_to "Đăng xuất", destroy_user_session_path, method: :delete, :class=>'btn btn-outline-success' %> 
<% else %>
    <a style="margin-left : 10px" class="btn btn-outline-success" href="/users/sign_in">Đăng nhập</a> 
<% end %>

  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>


    </div>
   
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>